### ISSUE TITLE
Stoped working

### ISSUE THREAD

**Issue by jeffersonblizz** [RSully/Find-My-iPhone---PHP-API#1]
Hello my findmyiphone.php stopped working after the api update you have notion of what you have to pack after the update?

Follow the link to my complete code http://pastebin.com/FhHQKJF0

**Comment by RSully** [comment]
Sorry this project has been deprecated and I don't have much of a need to rewrite this right now.

**Comment by aminetiaret** [comment]
Can't autoremove devices with new update
